### ISSUE TITLE
Animation Color Error

### ISSUE THREAD

**Issue by Jokelo** [marian42/pixelpi#1]
Whenever I try to load a image using example_cycle.py the color of the animation is different than what it should be.

For example this animation:

[Block.zip](https://github.com/marian42/pixelpi/files/358549/Block.zip)

Looks like this on my matrix:

![224938928725234481-account_id 1](https://cloud.githubusercontent.com/assets/19256572/16755031/731b9180-47c6-11e6-870d-6ba6d4188d51.jpg)

Any ideas on how to fix this? Any help would be much appreciated.

**Comment by derblub** [comment]
Looks like a wrong wiring to me - check your joints.

**Comment by marian42** [comment]
I don't have an idea what it could be. It seems that the green color channel gets through correctly. That suggests that it's working on the software side and there is a hardware issue.

The WS281x library has an invert option, although on the photo it doesn't quite look like it's inverted.
It would also be interesting to know what you see with the `stdrandtest.py` that is provided with the WS2812 library.

Sorry I'm not being super helpful... I think your best bet is asking on the Raspberry Pi Forum. I hope you get it resolved!

**Comment by Jokelo** [comment]
Thanks for the responses. Sorry if my initial post was vague. I am using a ws2812B LED strip [from eBay](http://www.ebay.com/itm/WS2812B-5050-RGB-LED-Strip-5M-150-300-Leds-144-30LED-M-Individual-Addressable-5V-/322058431958?var=&hash=item4afc2dadd6:m:mh5wcqoaZysJUIMArGeSHSg). Just to specify the problem, the green and the red LEDs were reversed (if the animation was supposed to be green the LEDs would show red and vice versa. Blue remained the same). 

After looking around and double checking my hardware I narrowed the problem down to the rpi_ws281x library. Specifically I discovered that within the [neopixels.py file](https://github.com/jgarff/rpi_ws281x/blob/master/python/neopixel.py) (the file that pixelpi imports from) there was a place  (line 52) where you could change the type of LEDs you had. After a bit more searching I found [this list ](https://github.com/jgarff/rpi_ws281x/blob/4f5d727222ef4e48608d43c51b3b932c0840813d/ws2811.h#L45-L64)(Lines 53-59) of possible color configurations (RGB, GRB, GBR, etc). After a bit of trial and error (changing the strip_type, sudo python setup.py install within the rpi_ws281x/python directory every time I changed the strip_type, and loading up example_animation.py in pixelpi to see if the change worked) I finally got the right colors. I believe the strip_type that eventually worked for me was WS2811_STRIP_BRG though I can't quite remember for sure. 

This error is too bizarre as the rpi_ws281x library seems to indicate that ws2811 are equivalant to ws2812/12B. I guess this means that the library for a RGB ws2812B is the same as the library for a BRG ws2811?

At any rate I'm glad to have it resolved. Thanks again.
