### ISSUE TITLE
adafruit-circuitpython-neopixel  not available for python2.7

### ISSUE THREAD

**Issue by cventastic** [marian42/pixelpi#2]
Do you know how to find a working python2.7 neopixel library?

**Comment by marian42** [comment]
Did you try the [one linked in the readme](https://github.com/jgarff/rpi_ws281x)? I haven't worked on the project for quite some time, but it looks like the neopixel library didn't change either.

**Comment by cventastic** [comment]
Thanks for an answer on this old project. 
We don't have problems installing the python binding via pip install rpi_ws281x . 
But there is no neopixel library included. 

import rpi_ws281x
import neopixel
ImportError: No module named neopixel

For that we need:
`pip install adafruit-circuitpython-neopixel` 
(as seen on https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage). 
But its not available on python2.7 anymore:
`No matching distribution found for Adafruit-Blinka (from adafruit-circuitpython-neopixel)`
So I think we need the neopixel library for python2.7. But we cant find it.

**Comment by marian42** [comment]
I don't know if there is a place to get the old library. Maybe you can ask on the adafruit forum.

However, there is not a lot that happens in the neopixel python library. Maybe it's possible to just replicate the behaviour of the neopixel library.

I made a C++ implementation where the screen class uses the ws281x library directly:
https://github.com/marian42/ledcpp/blob/master/cpp/screen/Screen.cpp

If you compare it to the python version, it's not very different:
https://github.com/marian42/pixelpi/blob/master/screen/screen.py

Maybe you can figure out a way to get rid of the neopixel dependency.

Alternatively, you could try to port this project to python3. I don't know how much effort that is but I suspect it's not too much work.
Unfortunately, I currently don't have the time to do either of these myself.

Also, as a warning, if you want to work with the code in this repository, it is not really plug and play. You might need to change a few things to get it to do what you want. 

Good luck!

**Comment by cventastic** [comment]
I figured, I'd have to port it to python3 but now I will try wrapping around the ws281x library. 
Thanks for the help.
Schoenen Freitag :)
